site_name: Implementation Plans
site_url: ''
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
plugins:
- glightbox
nav:
- Home: index.md
- Plans:
  - 'Issue #43 - Redirect unverified users to verification page': plans/issue-43-plan.md
